#!/usr/bin/env bash

bake_require github.com/kyleburton/bake-recipies/emacs/cider.sh

bake_task install-all "Install...everything"
function install-all () {
  test -d software || mkdir software
  emacs-install-cider     || echo "No Network?"
  emacs-install-ac-cider  || echo "No Network?"

  if [ ! -e $HOME/.emacs ]; then
    ln -s $(pwd)/.emacs $HOME/.emacs
  fi

  test -d $HOME/.emacs.d || mkdir $HOME/.emacs.d
}
